
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTOYCOMA = 6;
  public static final int DIFERENCIA = 9;
  public static final int DOSPUNTOS = 4;
  public static final int CONJUNTO = 16;
  public static final int HASTA = 14;
  public static final int INTERSECCION = 8;
  public static final int FLECHA = 5;
  public static final int OPERA = 19;
  public static final int ID = 15;
  public static final int COMA = 13;
  public static final int EOF = 0;
  public static final int ELEMENTOS_EVALUAR = 17;
  public static final int CONJ = 18;
  public static final int PAR_IZQ = 11;
  public static final int UNION = 7;
  public static final int error = 1;
  public static final int PAR_DER = 12;
  public static final int COMPLEMENTO = 10;
  public static final int LLAVE_IZQ = 2;
  public static final int EVALUAR = 20;
  public static final int LLAVE_DER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "DOSPUNTOS",
  "FLECHA",
  "PUNTOYCOMA",
  "UNION",
  "INTERSECCION",
  "DIFERENCIA",
  "COMPLEMENTO",
  "PAR_IZQ",
  "PAR_DER",
  "COMA",
  "HASTA",
  "ID",
  "CONJUNTO",
  "ELEMENTOS_EVALUAR",
  "CONJ",
  "OPERA",
  "EVALUAR"
  };
}

